-- ========================================
-- ProjectRename 功能数据库初始化脚本
-- ========================================

-- 1. 创建项目重命名历史表
CREATE TABLE IF NOT EXISTS `project_rename_history` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `project_path` VARCHAR(500) NOT NULL COMMENT '项目根路径',
    `old_package_name` VARCHAR(200) COMMENT '旧包名前缀',
    `new_package_name` VARCHAR(200) COMMENT '新包名前缀',
    `old_project_name` VARCHAR(100) COMMENT '旧项目标识名',
    `new_project_name` VARCHAR(100) COMMENT '新项目标识名',
    `old_table_prefix` VARCHAR(100) COMMENT '旧表名前缀',
    `new_table_prefix` VARCHAR(100) COMMENT '新表名前缀',
    `status` VARCHAR(20) NOT NULL COMMENT '状态：SUCCESS/FAILED/ROLLED_BACK',
    `error_message` TEXT COMMENT '错误信息',
    `backup_path` VARCHAR(500) COMMENT '备份路径',
    `affected_files_count` INT DEFAULT 0 COMMENT '影响的文件数量',
    `affected_tables_count` INT DEFAULT 0 COMMENT '影响的表数量',
    `execution_time_seconds` INT COMMENT '执行耗时（秒）',
    `description` VARCHAR(500) COMMENT '操作描述',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_project_path` (`project_path`),
    INDEX `idx_status` (`status`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目重命名历史记录表';

-- 2. ${businessName}管理菜单配置（基于 ContiNew Admin 系统设计）
SET @parentId = 1000;

-- 插入"系统工具"父菜单（如果不存在）
INSERT IGNORE INTO `sys_menu`
    (`id`, `title`, `parent_id`, `type`, `path`, `name`, `component`, `redirect`, `icon`, `is_external`, `is_cache`, `is_hidden`, `permission`, `sort`, `status`, `create_user`, `create_time`)
VALUES
    (@parentId, '系统工具', 0, 1, '/system', 'system', NULL, NULL, 'tool', b'0', b'0', b'0', NULL, 8, 1, 1, NOW());

-- 设置系统工具菜单ID
SET @systemToolsId = @parentId;

-- ${businessName}管理菜单
SET @${apiName}MenuId = ${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c};
INSERT INTO `sys_menu`
    (`id`, `title`, `parent_id`, `type`, `path`, `name`, `component`, `redirect`, `icon`, `is_external`, `is_cache`, `is_hidden`, `permission`, `sort`, `status`, `create_user`, `create_time`)
VALUES
    (@${apiName}MenuId, '${businessName}管理', @systemToolsId, 2, '/system/${apiName}', '${classNamePrefix}', 'system/${apiName}/index', NULL, 'folder-open', b'0', b'0', b'0', NULL, 1, 1, 1, NOW());

-- ${businessName}管理按钮权限
INSERT INTO `sys_menu`
    (`id`, `title`, `parent_id`, `type`, `permission`, `sort`, `status`, `create_user`, `create_time`)
VALUES
    (${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c}, '预览重命名', @${apiName}MenuId, 3, '${apiModuleName}:${apiName}:preview', 1, 1, 1, NOW()),
    (${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c}, '执行重命名', @${apiName}MenuId, 3, '${apiModuleName}:${apiName}:execute', 2, 1, 1, NOW()),
    (${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c}, 'Java文件重命名', @${apiName}MenuId, 3, '${apiModuleName}:${apiName}:java-rename', 3, 1, 1, NOW()),
    (${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c}, '配置文件更新', @${apiName}MenuId, 3, '${apiModuleName}:${apiName}:config-update', 4, 1, 1, NOW()),
    (${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c}, '生成脚本', @${apiName}MenuId, 3, '${apiModuleName}:${apiName}:script', 5, 1, 1, NOW()),
    (${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c}, '验证结果', @${apiName}MenuId, 3, '${apiModuleName}:${apiName}:verify', 6, 1, 1, NOW()),
    (${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c}, '回滚操作', @${apiName}MenuId, 3, '${apiModuleName}:${apiName}:rollback', 7, 1, 1, NOW()),
    (${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c}, '查看历史', @${apiName}MenuId, 3, '${apiModuleName}:${apiName}:history', 8, 1, 1, NOW()),
    (${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c}, '删除历史', @${apiName}MenuId, 3, '${apiModuleName}:${apiName}:delete', 9, 1, 1, NOW());

<#---- PostgreSQL（切换 PostgreSQL 数据库时请注释掉其他数据库脚本，并解开此段注释）-->
<#--DO $$-->
<#--    DECLARE project_rename_history_id_seq INT8 := ${statics["cn.hutool.core.util.IdUtil"].getSnowflakeNextId()?c};-->
<#--BEGIN-->

<#--    -- 创建项目重命名历史表-->
<#--    CREATE TABLE IF NOT EXISTS "project_rename_history" (-->
<#--        "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,-->
<#--        "project_path" VARCHAR(500) NOT NULL,-->
<#--        "old_package_name" VARCHAR(200),-->
<#--        "new_package_name" VARCHAR(200),-->
<#--        "old_project_name" VARCHAR(100),-->
<#--        "new_project_name" VARCHAR(100),-->
<#--        "old_table_prefix" VARCHAR(100),-->
<#--        "new_table_prefix" VARCHAR(100),-->
<#--        "status" VARCHAR(20) NOT NULL,-->
<#--        "error_message" TEXT,-->
<#--        "backup_path" VARCHAR(500),-->
<#--        "affected_files_count" INT DEFAULT 0,-->
<#--        "affected_tables_count" INT DEFAULT 0,-->
<#--        "execution_time_seconds" INT,-->
<#--        "description" VARCHAR(500),-->
<#--        "create_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,-->
<#--        "update_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP-->
<#--    );-->

<#--    -- 创建索引-->
<#--    CREATE INDEX IF NOT EXISTS "idx_project_path" ON "project_rename_history" ("project_path");-->
<#--    CREATE INDEX IF NOT EXISTS "idx_status" ON "project_rename_history" ("status");-->
<#--    CREATE INDEX IF NOT EXISTS "idx_create_time" ON "project_rename_history" ("create_time");-->

<#--END $$;-->

-- 3. 示例数据（可选）
-- 插入一些示例历史记录用于测试
INSERT INTO `project_rename_history`
    (`project_path`, `old_package_name`, `new_package_name`, `old_project_name`, `new_project_name`, `status`, `description`, `affected_files_count`, `execution_time_seconds`)
VALUES
    ('D:/projects/demo-app', 'com.old', 'com.new', 'demo', 'myapp', 'SUCCESS', '测试项目重命名', 150, 45),
    ('D:/projects/sample-project', 'com.air', 'com.continew', 'sample', 'project', 'FAILED', '测试失败场景', 0, 5);

-- 4. 权限配置提示
-- 需要为以下角色分配相应的菜单权限：
-- - 系统管理员：拥有所有权限
-- - 开发者：拥有预览、执行、验证、查看历史权限
-- - 运维：拥有执行、回滚、查看历史权限

-- 5. 索引优化建议
-- 如果数据量大，可以考虑添加以下复合索引：
-- ALTER TABLE `project_rename_history` ADD INDEX `idx_project_status_time` (`project_path`, `status`, `create_time`);
-- ALTER TABLE `project_rename_history` ADD INDEX `idx_status_time` (`status`, `create_time`);